language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-6 g++-6 -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6; fi

# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - gcc-6
#     - g++-6

compiler:
  - clang
  - gcc

os:
  - osx
  - linux

install: true

osx_image: xcode8.2

dist: trusty
sudo: required

matrix:
  exclude:
  - os: osx
    compiler: gcc
  - os: linux
    compiler: clang

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./apps/build.linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./apps/build.osx.sh; fi
