-- Widget Custom data and order, order = 0 disabled widget
return {
	data = {},
	order = {
		["Heroes Right Click"] = 12345,
		["Hide commands"] = 1,
		["Keep Morpheds Selected"] = 2,
		["Kernel Panic A.I. Debug"] = 0,
		["Kernel Panic Automatic Tip Dispenser"] = 11,
		["Kernel Panic Build Bar"] = 3,
		["Kernel Panic Console Commands"] = 4,
		["Kernel Panic Default Commands"] = 8,
		["Kernel Panic Geos Highlight"] = 9,
		["Kernel Panic Hotkeys"] = 12345,
		["Kernel Panic MidKnight's tooltip background"] = 5,
		["Kernel Panic Mission Briefing"] = 8,
		["Kernel Panic O.N.S. help tips"] = 12345,
		["Kernel Panic Tooltip"] = 12,
		["Kernel Panic autospam"] = 6,
		["Set Spring-wide settings and Lua WhiteList"] = 0,
		["Spring Direct Launch 2"] = 13,
		TeamDiedMessages = 10,
		["Write GameState"] = 7,
		["noResBar NoMoveWarnings"] = 12345,
	},
}
